# Part 1

Calculate the sum of 4 and 10 below.

In [1]:
4 + 10

14

Assign the value 24 to x.

In [2]:
x = 24

Assign the value x-squared to y.

In [3]:
y = x^2

Check that y is equivalent to x-squared.

In [4]:
y == x^2

True

Create a numeric, character, and logical variable, then check their classes using the type() function.

In [8]:
SM_numeric = 1227
type(SM_numeric)  # R: class()

# R: numeric
# Python: int / float

int

In [9]:
SM_character = "Seokbin Moon"
type(SM_character)  # R: class()

# R: character
# Python: str

str

In [10]:
SM_logical = (1227+1227==1)|(1227*0==0)
type(SM_logical)  # R: class()

# R: logical
# Python: bool

bool

# Part 2

This vector has the average high temperatures in Fort Collins for each month. Please run the line below.

In [12]:
temperature_fc = tuple([44, 47, 55, 62, 71, 80, 87, 84, 76, 64, 51, 43])
# I used 'tuple' because each value is fixed(immutable).

Create a vector called "months" with elements Jan-Dec.

In [13]:
months = tuple(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

Assign the names of the months to the "temperature_fc" vector.

In [16]:
temperature_fc_dict = dict(zip(months, temperature_fc))
temperature_fc_dict

# R: names(temperature_fc) <- months

{'Jan': 44,
 'Feb': 47,
 'Mar': 55,
 'Apr': 62,
 'May': 71,
 'Jun': 80,
 'Jul': 87,
 'Aug': 84,
 'Sep': 76,
 'Oct': 64,
 'Nov': 51,
 'Dec': 43}

Calculate and print the mean temperature in Fort Collins over the year.

In [20]:
import numpy as np
np.mean(temperature_fc)

# R: print(mean(temperature_fc))
# In Python, we have to import 'numpy'

np.float64(63.666666666666664)

Create a logical vector called "above_freezing" that returns TRUE if the temperature of a month is above 32 degrees, FALSE otherwise.

In [22]:
above_freezing = np.array(temperature_fc) > 32
above_freezing

# R: above_freezing <- temperature_fc > 32
# np.array converts the tuple to a NumPy array, enabling element-wise comparison (> 32).

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

This vector has the average high temperatures in Atalanta each month

In [23]:
temperature_atlanta = tuple([52, 57, 65, 73, 80, 87, 89, 88, 82, 73, 63, 55])

Assign the names of the months to the "temperature_atlanta" vector.

In [24]:
temperature_atlanta_dict = dict(zip(months, temperature_atlanta))
temperature_atlanta_dict

{'Jan': 52,
 'Feb': 57,
 'Mar': 65,
 'Apr': 73,
 'May': 80,
 'Jun': 87,
 'Jul': 89,
 'Aug': 88,
 'Sep': 82,
 'Oct': 73,
 'Nov': 63,
 'Dec': 55}

Generate a logical vector called "atlanta_warmer" that returns TRUE if Atlanta was warmer than Fort Collins on a given month.

In [25]:
atlanta_warmer = np.array(temperature_fc) < np.array(temperature_atlanta)
atlanta_warmer

# R: atlanta_warmer <- temperature_fc < temperature_atlanta

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

Create a vector called "temperature_diff" that shows a difference in temperature between Atlanta and Fort Collins by month

In [27]:
temperature_diff = np.array(temperature_atlanta) - np.array(temperature_fc)
temperature_diff

array([ 8, 10, 10, 11,  9,  7,  2,  4,  6,  9, 12, 12])

Define a variable called "temperature_march" that pulls the March value out of the temperature_diff variable.

In [31]:
temperature_march = temperature_diff[2]
temperature_march

np.int64(10)